language: python

branches:
<<<<<<< HEAD
  only:
    - master
    - /\d+\.\d+\.\d+(-\S+)?$/
=======
  only: master
>>>>>>> Nitpick CI

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_SKIP="cp27-* cp35-* *-manylinux_i686"
    - CIBW_BEFORE_BUILD_LINUX=.travis/cibw-before-build-manylinux2014
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
    - CIBW_TEST_REQUIRES=tox
    - CIBW_TEST_COMMAND_LINUX="tox -c /project"

jobs:
  include:
    - services: docker

install: pip install twine cibuildwheel

script: cibuildwheel --output-dir=dist

deploy:
  skip_cleanup: true
  provider: script
  script: twine upload dist/*.whl
  on:
    tags: true
