language: python

branches:
  only:
    - master
    - /^\d+(\.\d+)+((a|b|rc)\d+)?(\.post\d+)?(\.dev\d+)?$/

env:
  global:
    - TWINE_USERNAME=__token__
    - MACOSX_DEPLOYMENT_TARGET=10.9
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
    - CIBW_BEFORE_BUILD_LINUX=.ci/before-build-manylinux2014
    - CIBW_BEFORE_BUILD_MACOS=.ci/before-build-macos
    - CIBW_REPAIR_WHEEL_COMMAND_MACOS=".ci/repair-whl-macos {wheel} {dest_dir}"
    - CIBW_TEST_REQUIRES_LINUX=tox
    - CIBW_TEST_COMMAND_LINUX="tox -c /project"

addons:
  homebrew:
    packages:
      - openal-soft
      - libvorbis
      - opusfile
      - libsndfile

install: python3 -m pip install twine cibuildwheel

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      language: shell
      env: CIBW_BUILD=cp36-macosx_x86_64
    - os: osx
      osx_image: xcode11.3
      language: shell
      env: CIBW_BUILD=cp37-macosx_x86_64
    - os: osx
      osx_image: xcode11.3
      language: shell
      env: CIBW_BUILD=cp38-macosx_x86_64
    - services: docker
      env: CIBW_BUILD=cp36-manylinux_x86_64
    - services: docker
      env: CIBW_BUILD=cp37-manylinux_x86_64
    - services: docker
      env: CIBW_BUILD=cp38-manylinux_x86_64

script: python3 -m cibuildwheel --output-dir=dist

deploy:
  skip_cleanup: true
  provider: script
  script: twine upload dist/*.whl
  on:
    tags: true
