#!/bin/sh
set -ev
git clone https://github.com/kcat/alure
cd alure/build
OPENALDIR=$(brew --prefix openal-soft) cmake -DCMAKE_FIND_FRAMEWORK=NEVER ..
cmake --build . --config Release
sudo cmake --install .
