name: Deploy documentation

on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/*
    - docs/**
    - src/**

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout palace
      uses: actions/checkout@v2

    - name: Checkout alure
      uses: actions/checkout@v2
      with:
        repository: kcat/alure
        path: alure

    - name: Install dependencies
      run: |
        sudo apt install \
          cmake libopenal-dev libvorbis-dev libopusfile-dev libsndfile1-dev
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -S alure -B alure/build
        sudo cmake --build alure/build --parallel `nproc` --target install
        rm -fr alure
        python -m pip install Sphinx sphinx_rtd_theme .

    - name: Build site
      working-directory: docs
      run: make html

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
